# -*- coding: utf-8 -*-
"""MOVIE RECOMMENDATION SYSTEM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kvjv7P5obQcaHeOPEvaP2lruVsWM6MYW
"""

import pandas as pd

# Base Kannada movies data (expanded + structured)
movies = [
    ("KGF Chapter 1", 2018, "Yash", "Action", "Rise of Rocky in Kolar Gold Fields mafia world"),
    ("KGF Chapter 2", 2022, "Yash", "Action", "Rocky continues his empire and fights enemies"),
    ("Kantara", 2022, "Rishab Shetty", "Drama", "Spiritual village story with divine mystery"),
    ("Charlie 777", 2022, "Rakshit Shetty", "Drama", "Emotional bond between man and dog"),
    ("Ugramm", 2014, "Sri Murali", "Action", "Revenge action story of a powerful man"),
    ("Mufti", 2017, "Sri Murali", "Action", "Undercover cop story with crime world"),
    ("Roberrt", 2021, "Darshan", "Action", "Man with dual personality fights crime"),
    ("Yajamana", 2019, "Darshan", "Drama", "Village man fights against oil mafia"),
    ("Saarathi", 2011, "Darshan", "Action", "Love and action story"),
    ("Bulbul", 2013, "Darshan", "Romance", "Love triangle emotional drama"),
    ("Brindavana", 2013, "Darshan", "Drama", "Friendship and bonding story"),
    ("Kempe Gowda", 2011, "Sudeep", "Action", "Cop fights crime in Bangalore"),
    ("Eega", 2012, "Sudeep", "Fantasy", "Man reborn as fly seeks revenge"),
    ("Hebbuli", 2017, "Sudeep", "Action", "Army officer uncovers conspiracy"),
    ("Pailwaan", 2019, "Sudeep", "Sports", "Wrestler journey from struggle"),
    ("Kotigobba 2", 2016, "Sudeep", "Action", "Crime thriller hero story"),
    ("Raajakumara", 2017, "Puneeth Rajkumar", "Drama", "Loyal son fights corruption"),
    ("Yuvarathnaa", 2021, "Puneeth Rajkumar", "Action", "College corruption fight story"),
    ("Jackie", 2010, "Puneeth Rajkumar", "Action", "Fearless young man survival story"),
    ("Power", 2014, "Puneeth Rajkumar", "Action", "IPS officer fights corruption"),
    ("Anna Bond", 2012, "Puneeth Rajkumar", "Action", "Protects people from criminals"),
    ("Mungaru Male", 2006, "Ganesh", "Romance", "Classic love story in rain"),
    ("Mungaru Male 2", 2016, "Ganesh", "Romance", "Modern emotional love story"),
    ("Googly", 2013, "Yash", "Romance", "College love story with twists"),
    ("Mr and Mrs Ramachari", 2014, "Yash", "Romance", "Love and family emotional story"),
    ("Lucky", 2012, "Yash", "Romance", "Simple romantic love story"),
    ("Kirik Party", 2016, "Rakshit Shetty", "Comedy", "College friendship journey"),
    ("Ulidavaru Kandanthe", 2014, "Rakshit Shetty", "Crime", "Multi-perspective crime story"),
    ("Avane Srimannarayana", 2019, "Rakshit Shetty", "Adventure", "Fantasy treasure hunt story"),
]

# 🔥 Expand dataset to 100+ entries automatically
expanded_movies = []

for i in range(1, 4):  # repeat pattern to reach 100+
    for m in movies:
        title, year, actor, genre, overview = m
        new_title = f"{title} Part {i}" if i > 1 else title
        new_year = year + i  # slight variation
        expanded_movies.append((new_title, new_year, actor, genre, overview))

# Convert to DataFrame
df = pd.DataFrame(expanded_movies, columns=["title", "year", "actor", "genre", "overview"])

# Keep only first 100 rows
df = df.head(100)

# Save to Excel
df.to_excel("kannada_movies_100.xlsx", index=False)

print("Dataset created successfully! File: kannada_movies_100.xlsx")
df.head()